### ISSUE TITLE
Raspberry Pi OS en 64 bits

### ISSUE THREAD

**Issue by ClubACNews** [apiou/vps_installation#1]
Bonjour Stéphane,
J'essaye de procéder à l'installation d'un serveur web à partir de votre tuto mais je remarque des incohérences par rapport à la version 64 bits préconisée et les paquets à installer disponibles dans les dépots.
Par exemple le package "rar" n'est pas disponible en 64 bits pour une version bullseye (64 bits) mais la release inférieure buster n'existe pas encore en version 64 bits sur https://www.raspberrypi.com/software/operating-systems/ 

Je pense qu'il y a des précisions à apporter à cette documentation déjà compléte mais je ne suis pas assez compétent en linux pour les y apporter. Je manque beaucoup d'expérience.
Je propose de reprendre point par point cette doc et d'y noter les points bloquants pour que vous apportez les bonnes réponses et qu'elle soit utilisable pour un novice.
François

**Comment by stefapi** [comment]
Bonjour,
Cette documentation a été écrite initialement comme aide mémoire pour mon propre usage. Elle date de 2020 par rapport aux packages et en effet les choses ont un peu évoluées.

Je prendrai en compte avec beaucoup de plaisir vos commentaires et remarques afin de compléter, éclaircir cette documentation, le but étant d'enrichir cette doc, la maintenir à jour (package et sécurité) et la faire vivre.

Merci à vous

Stéphane

**Comment by ClubACNews** [comment]
Bonjour,
Je ne pense pas procéder à la mise à jour de votre documentation car la version PHP sur un Raspberry-Pi n'existe que jusqu'à la version 7.4.
J'ai besoin de versions supérieures pour un site en Joomla 4.
Je possède également une carte Cubietruck, je vais reprendre mon travail sur cette carte car PHP 8.2 existe pour cette mono-carte.
Bonne journée.
François

**Comment by stefapi** [comment]
Doc maintenant à jour. La version de PHP supportée va maintenant de la 5.6 à la 8.2 et vous avez le choix de la version que vous voulez utiliser dans ispconfig selon vos besoins !
