### ISSUE TITLE
update de la documentation de la blueseyes vers bookworm

### ISSUE THREAD

**Issue by ClubACNews** [apiou/vps_installation#2]
Bonjour M. Apiou,

Je suis tombé sur votre doc et je tente une installation d'un serveur web avec ispc-config en gestionnaire.
Ma config Raspi 4 8Go de ram et 1ssd de 1To sur boitier Argon One M.2 ce qui me permet de booter sans la µ-SD.

Mon OS est un lite 64 bits en version BookWorm.

Page 27 de votre doc version 1.5 de janvier 2023 lors de l'installation initiale des outils :
  * getmail4 n'existe pas, il faut le remplacer par getmail6,
  * php-gettext n'existe pas, il faut le remplacer par php-php-gettext,
  * j'ai un message que php-recode n'existe plus et il ne trouve pas le paquet php7.3-xls
 -> Pour la non installation de ces 2 paquet cela est-il génant pour la suite des opérations ?

Au point 4 de ce chapitre, il faut configurer les mails, je pige pas trop quoi mettre de mon nom de host (nom de la machine ?) comme Nom de courrier. Mon nom de domaine est "ac-news.fr" et le nom de la machine est "club-acnews". Lequel des 2 ?

Votre doc semble ben faites mais j'ai quelque peu de mal avec les hostname, host, DNS, FQDN, ...
Pouriiez-vous y ajouter à partir d'un nom de domaine "bidon" des exemples de nomage pour le host, hostname, ...... afin que l'on puisse faire l'adaptation à partir de notre nom de domaine.
Merci
F. PARTY

Je vais retrograder vers un OS blueeyes pour ré-essayer votre doc.
N.B. : J'ai quitté une carte Cubietruck car ne démarre que sur SD et j'ai eu pas mal de soucis à cause de nombre d'écriture/lecture de cette SD. Je suis passé sur raspberry pour m'affranchir de ces problèmes qui abiment le µ-SD. Je ne dispose plus d'un scrip pour installer ISCP et je dois donc tout refaire à la mano.
Je peux faire doc pour compléter la votre de comment rendre un raspberry-pi bootable sur un SSD et là le serveur web sans soucis de SD devient intéressant.

**Comment by stefapi** [comment]
La documentation est maintenant à jour avec la dernière version de Debian.
L'utilisation d'une Debian Linux 64 est maintenant le standard dans cette documentation que ce soit pour l'installation d'un VPS ou pour un Raspberry.
La documentation pour le serveur interne de la maison (nommé homeserver qui contient un PIHole et divers outils de gestion du réseau de la maison) n'est pas encore complètement à jour.
