### ISSUE TITLE
Test de la documentation

### ISSUE THREAD

**Issue by ClubACNews** [apiou/vps_installation#3]
Bonjour,
Merci de votre update.
J'ai reçu, fin de semaine dernière, raspberry-pi 5 8Go et son boitier Argon 3 pour DD SSD (à commander !).
Je suis en vacances jusqu'au 28 avril 2024 et je vous propose de tester votre doc sur la dernière version de RaspBerry-Pi.
Il se peut que ça déborde en mai car j'avais pas prévu cette activité en plus.
Laissez le ticket ouvert, je le compléterai au fur et à mesure des éléments problématiques (si il y en a !) 
Merci.

**Comment by ClubACNews** [comment]
Bonjour,
Je bloque sur la forme que doit avoir le fichier hosts au chapitre 7 Paragaphe 7.1. Vous est-il possible d'y ajouter un exemple avec le nom de domaine "example.com". Dans l'ancienne doc, l'exemple du fichier à obtenir apparaissait de mémoire.
Faut-il y intégrer l'adresse "mail.exeample.com" dedans ? L'encart d'information donne le doute. 
Merci
Je viens de retrouver le pdf de la version 1.5 et il n'y avait pas d'exemple de fichier à obtenir. J'ai tellement essayé de tutos que j'ai confondu. Vous est-il possible d'y ajouter ?
Je poursuis l'installe avec ces infos dans le fichier hosts : 
#127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       example.com
Est-ce bien cela ?
Merci
J'ai retrouve le site concernant ce paramétrage, je fais copie écran
![hostname](https://github.com/stefapi/vps_installation/assets/31184595/7f8e12e7-7e67-4c8e-92a9-839ee7f3c446)

**Comment by ClubACNews** [comment]
Re,
Je suis arrivé au chapitre 8 de l'installation de ISCPConfig.
En effet, la configuration du host nécessite un exemple concret car par la commande "hostname -f, je n'obtiens pas le résultat attendu. 
Je n'engage pas l'installation d'ISCPConfig pour le moment dans l'attente de ce précisions nécessaires.
Je cherche en // comment définir corectemet le fichier "hosts".
Merci
François

**Comment by stefapi** [comment]
Bonsoir,
La réponse est un peu complexe car je n'ai pas trouvé de bonne solution.
Idéalement il serait bien de mettre dans le fichier host le nom de la machine suivie du nom de domaine comme l'exemple que vous donnez.
192.168.2.250 aalpi01.example.com aalpi01
Cependant, si vous décidez, comme je l'ai fait de mon coté,  d'avoir un nom DNS de serveur de mail en mail.example.com (entréee MX du domaine), il est indispensable pour que la messagerie soit correctement configurée pour les sites de tests tels que : https://mxtoolbox.com/emailhealth (catégorie mail server) que le nom du serveur défini dans le serveur de mail corresponde au hostname.
Je n'ai donc pas trouvé d'autre façon de faire que de mettre ceci:
192.168.2.250 mail.example.com mail

En espérant avoir été assez clair.

**Comment by ClubACNews** [comment]
Bonjour,
J'ai tardé à m'y remettre car la procédure m'apparaissait longue et le temps me manquait pour l'appliquer en une fois.
En fait, elle n'est pas si longue avec l'auto-installer d'ISCPConfig. Il y a pleins de chapitres à passer en fait (j'avais pas vu ce saut !)
La doc est bonne et fonctionnelle.
J'ai installé 2 serveurs Web différents sur des Raspberry-Pi 5 avec 8 Go de Ram associé à un SSD de 1 Terra dans un boitier "Argon One V3". J'utilise Joomla en V4.
Un grand merci car finis les pbs de microSD et les données perdues dues aux nombreuses écritures/Lecture dessus. (Je boot directement sur le SSD maintenant).
François
Bonnes vacances si c'est la cas
